apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: iks-test
  name: iks-test
spec:
  ports:
  - name: 80-5000
    port: 80
    protocol: TCP
    targetPort: 5000
  selector:
    app: iks-test
  type: NodePort
status:
  loadBalancer: {}    
