import logging
import os
import time
from contextlib import contextmanager
from typing import Tuple, Optional

import psycopg2
from psycopg2 import OperationalError, ProgrammingError
from psycopg2.extras import DictCursor
from psycopg2.pool import ThreadedConnectionPool

logging.basicConfig(level=logging.INFO)

_pool: Optional[ThreadedConnectionPool] = None
_MIN_CONN = 0
_MAX_CONN = 10
_RETRIES = 3
_RETRY_DELAY = 0.5


def get_db_credentials():
    return {
        "dbname": os.environ.get("DB_NAME"),
        "user": os.environ.get("DB_USERNAME"),
        "password": os.environ.get("DB_PASSWORD"),
        "host": os.environ.get("DB_HOST"),
        "port": os.environ.get("DB_PORT"),
    }


def _create_pool():
    creds = get_db_credentials()
    return ThreadedConnectionPool(_MIN_CONN, _MAX_CONN, **creds)


def get_pool():
    global _pool
    if _pool is None:
        _pool = _create_pool()
    return _pool


def close_pool():
    global _pool
    if _pool is not None:
        _pool.closeall()
        _pool = None


@contextmanager
def get_connection():
    pool = get_pool()
    conn = pool.getconn()
    try:
        yield conn
    finally:
        pool.putconn(conn)


def get_result(query: str, param: Tuple = None):
    try:
        for attempt in range(_RETRIES):
            try:
                with get_connection() as conn:
                    with conn.cursor() as cursor:
                        if param is None:
                            cursor.execute(query)
                        else:
                            cursor.execute(query, param)
                        try:
                            return cursor.fetchall() if cursor.rowcount >= 0 else []
                        except ProgrammingError:
                            return []
            except OperationalError as e:
                logging.warning("DB operational error (attempt %d/%d): %s", attempt + 1, _RETRIES, e)
                if attempt < _RETRIES - 1:
                    time.sleep(_RETRY_DELAY * (2 ** attempt))
                    continue
                raise
        return []
    except Exception as e:
        logging.error("Error executing query: %s with params: %s", query, param)
        logging.error(e)
        raise


def get_result_dict(query: str, param: Tuple = None):
    try:
        for attempt in range(_RETRIES):
            try:
                with get_connection() as conn:
                    with conn.cursor(cursor_factory=DictCursor) as cursor:
                        if param is None:
                            cursor.execute(query)
                        else:
                            cursor.execute(query, param)
                        try:
                            return cursor.fetchall()
                        except ProgrammingError:
                            return []
            except OperationalError as e:
                logging.warning("DB operational error (attempt %d/%d): %s", attempt + 1, _RETRIES, e)
                if attempt < _RETRIES - 1:
                    time.sleep(_RETRY_DELAY * (2 ** attempt))
                    continue
                raise
        return []
    except Exception as e:
        logging.error("Error executing query: %s with params: %s", query, param)
        logging.error(e)
        raise


def init_db():
    createUserCredentials = """CREATE TABLE IF NOT EXISTS user_credentials (
        id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
        email VARCHAR(50) NOT NULL,
        password VARCHAR(100) NOT NULL);"""

    createUserProfile = """CREATE TABLE IF NOT EXISTS user_profiles (
        id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
        login_id INT NOT NULL,
        name VARCHAR(30),
        budget INT DEFAULT 0,
        phone VARCHAR(30),
        profession VARCHAR(30),
        alert BOOLEAN DEFAULT FALSE,
        FOREIGN KEY (login_id) REFERENCES USER_CREDENTIALS(id) ON DELETE CASCADE);"""

    createUserEvents = """CREATE TABLE IF NOT EXISTS user_events(
            id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
            login_id INT NOT NULL,
            name VARCHAR(30),
            budget INT DEFAULT 0,
            FOREIGN KEY (login_id) REFERENCES USER_CREDENTIALS(id) ON DELETE CASCADE);"""

    createUserTransactions = """CREATE TABLE IF NOT EXISTS user_transactions (
        id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
        login_id INT NOT NULL,
        transaction NUMERIC NOT NULL,
        mode VARCHAR(20),
        category VARCHAR(20),
        event_id INT,
        datestamp DATE,
        note VARCHAR(50),
        FOREIGN KEY (login_id) REFERENCES USER_CREDENTIALS(id) ON DELETE CASCADE,
        FOREIGN KEY (event_id) REFERENCES USER_EVENTS(id) ON DELETE CASCADE);"""

    get_result(createUserCredentials)
    get_result(createUserProfile)
    get_result(createUserEvents)
    get_result(createUserTransactions)


class TransactionFormChoices:
    MODE = ["Online", "Credit Card", "Cash"]
    CATEGORY = ["Food", "Health", "Transport", "Shopping", "Entertainment", "Bills", "Debt Payment", "Other"]
